In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,3,4], [3,6,5]])
b = np.diag([2,6,7,4])
c = np.arange(10).reshape(2,5) #khởi tạo matrix [0;9] và đổi thành matrix 2 dòng 5 cột 
d = np.full((3,2,2),12) # khởi tạo 3 matrix 2*2 full 12 
e = np.array([3,4,5,2])
f = np.random.randint(0,10,(4,5)) # Khởi tạo matrix random từ  0 đến 10 shape (4,5)
g = np.random.randint(1,10,(1,5))
a


array([[1, 3, 4],
       [3, 6, 5]])

In [3]:
a = np.arange(16).reshape(4,4)
b = a[1:4 , 1:4]  # reference variable: lấy giao của dòng [1,4) và hàng [1,4)
b[0,0] = 20 #sẽ thay đổi tương   đương vs gtri tham chiếu b[0,0] tương đương với a[1,1]
c = a[:2,:2].copy() #ntn khi thay đổi c thì a, b sẽ  ko thay đổi 


In [4]:
b

array([[20,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [5]:
a = np.random.randint(10,100,(5,6))
a =  a.transpose() #chuyển dòng thành cột và ngược lại 
a.ndim #thông báo về chiều của array

2

#lọc data theo ĐK

In [6]:
a = np.random.seed(0)
a = np.random.randint(2,10000,(10,10))




In [7]:

a

array([[2734, 9847, 3266, 4861, 9227, 7893, 4375, 5876, 6746, 3470],
       [ 707, 2601, 2224, 7770, 2899, 9895,  539, 6218, 6923, 6038],
       [2165, 5074, 4853, 7879, 2048, 1873, 7601, 2498, 8293,  757],
       [ 799,  661, 3221, 8617, 7458, 3339, 2747, 4737, 8738, 6689],
       [ 716, 2294, 8345, 1209, 6174, 8996, 7223, 6023, 3624, 3562],
       [8950, 1643, 4986, 4355, 8624, 7252, 4189, 2661, 9783, 2958],
       [2253, 4422, 7110, 1073, 5253, 7014, 9398, 3920, 9361, 1686],
       [7100, 2959, 4471, 8754, 9799, 5797, 1474, 7265, 7367, 8450],
       [6003, 3764, 9010, 2437, 1636,  975, 4466, 8395, 2420, 3457],
       [6169, 5821, 6523, 6244, 7744, 9125, 6740, 2789, 7318, 4307]])

In [8]:
a = np.random.seed(0)
a = np.random.randint(3,10,(6,6))
print(a)
c = np.sort(a, axis=1) #sắp xếp tăng dần theo hàng 
print(c)
c = np.sort(a, axis=0)  #sắp xếp tăng dần theo cột 
print(c)


[[7 8 3 6 6 6]
 [4 6 8 5 7 9]
 [3 3 7 5 4 9]
 [9 3 4 8 4 8]
 [3 4 7 6 3 6]
 [8 9 3 5 6 3]]
[[3 6 6 6 7 8]
 [4 5 6 7 8 9]
 [3 3 4 5 7 9]
 [3 4 4 8 8 9]
 [3 3 4 6 6 7]
 [3 3 5 6 8 9]]
[[3 3 3 5 3 3]
 [3 3 3 5 4 6]
 [4 4 4 5 4 6]
 [7 6 7 6 6 8]
 [8 8 7 6 6 9]
 [9 9 8 8 7 9]]
